### ISSUE TITLE
Button styling broken after update

### ISSUE THREAD

**Issue by charliebrink** [angular/material-prefix-updater#11]
I've run the updater and most of the conversion went fine, except for my button styling that's broken now. 

![screen shot 2017-10-05 at 12 04 37 am](https://user-images.githubusercontent.com/7276052/31201956-e6359d44-a960-11e7-920f-4a0840f615f1.png)

I made sure to update the custom styling:

`mat-switcher -p path/to/project/tsconfig.json --extra-css 'src/styles/**/*.scss' `

**Comment by DevVersion** [comment]
Please resubmit with more information. e.g. how the button HTML will look like.
