### ISSUE TITLE
The tool does not update module name.

### ISSUE THREAD

**Issue by sheldonyss** [angular/material-prefix-updater#13]
After running the tool, I get below errors.
I have to update the module name manually.

Could not find updated prefix for identifier (MdButtonModule).
Could not find updated prefix for identifier (MdIconModule).
Could not find updated prefix for identifier (MdButtonToggleModule).
Could not find updated prefix for identifier (MdInputModule).
Could not find updated prefix for identifier (MdFormFieldModule).
Could not find updated prefix for identifier (MdSelectModule).
Could not find updated prefix for identifier (MdButtonModule).
Could not find updated prefix for identifier (MdSelectModule).
Could not find updated prefix for identifier (MdButtonToggleModule).
Could not find updated prefix for identifier (MdInputModule).
Could not find updated prefix for identifier (MdIconModule).
Could not find updated prefix for identifier (MdFormFieldModule).
Could not find updated prefix for identifier (MdCardModule).
Could not find updated prefix for identifier (MdToolbarModule).
Could not find updated prefix for identifier (MdButtonModule).
Could not find updated prefix for identifier (MdIconModule).
Could not find updated prefix for identifier (MdCheckboxModule).
Could not find updated prefix for identifier (MdSelectModule).
Could not find updated prefix for identifier (MdChipsModule).
Could not find updated prefix for identifier (MdAutocompleteModule).
Could not find updated prefix for identifier (MdMenuModule).
Could not find updated prefix for identifier (MdInputModule).
Could not find updated prefix for identifier (MdGridListModule).
Could not find updated prefix for identifier (MdListModule).
Could not find updated prefix for identifier (MdTooltipModule).
Could not find updated prefix for identifier (MdFormFieldModule).
Could not find updated prefix for identifier (MdSnackBarModule).
Could not find updated prefix for identifier (MdProgressBarModule).
Could not find updated prefix for identifier (MdTabsModule).
Could not find updated prefix for identifier (MdDialogModule).
Could not find updated prefix for identifier (MdCardModule).
Could not find updated prefix for identifier (MdSelectModule).
Could not find updated prefix for identifier (MdMenuModule).
Could not find updated prefix for identifier (MdToolbarModule).
Could not find updated prefix for identifier (MdInputModule).
Could not find updated prefix for identifier (MdButtonModule).
Could not find updated prefix for identifier (MdDialogModule).
Could not find updated prefix for identifier (MdAutocompleteModule).
Could not find updated prefix for identifier (MdProgressBarModule).
Could not find updated prefix for identifier (MdSnackBarModule).
Could not find updated prefix for identifier (MdIconModule).
Could not find updated prefix for identifier (MdChipsModule).
Could not find updated prefix for identifier (MdListModule).
Could not find updated prefix for identifier (MdTooltipModule).
Could not find updated prefix for identifier (MdCheckboxModule).
Could not find updated prefix for identifier (MdGridListModule).
Could not find updated prefix for identifier (MdTabsModule).
Could not find updated prefix for identifier (MdFormFieldModule).
Could not find updated prefix for identifier (MdCardModule).
Could not find updated prefix for identifier (MdToolbarModule).
Could not find updated prefix for identifier (MdButtonModule).
Could not find updated prefix for identifier (MdSnackBarModule).
Could not find updated prefix for identifier (MdMenuModule).
Could not find updated prefix for identifier (MdSelectModule).
Could not find updated prefix for identifier (MdInputModule).
Could not find updated prefix for identifier (MdCheckboxModule).
Could not find updated prefix for identifier (MdProgressBarModule).
Could not find updated prefix for identifier (MdListModule).
Could not find updated prefix for identifier (MdChipsModule).
Could not find updated prefix for identifier (MdTooltipModule).
Could not find updated prefix for identifier (MdAutocompleteModule).
Could not find updated prefix for identifier (MdGridListModule).
Could not find updated prefix for identifier (MdDialogModule).
Could not find updated prefix for identifier (MdIconModule).
Could not find updated prefix for identifier (MdFormFieldModule).
Could not find updated prefix for identifier (MdTabsModule).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdChipInputEvent).
Could not find updated prefix for identifier (MdChipInputEvent).
Could not find updated prefix for identifier (MD_DIALOG_DATA).
Could not find updated prefix for identifier (MD_DIALOG_DATA).
Could not find updated prefix for identifier (MD_DIALOG_DATA).
Could not find updated prefix for identifier (MD_DIALOG_DATA).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdSnackBar).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdDialog).
Could not find updated prefix for identifier (MdChipInputEvent).
Could not find updated prefix for identifier (MdChipInputEvent).

**Comment by lacolaco** [comment]
please downgrade material to beta.11 and try it again. mat-switcher cannot work w/ beta.12 AFAIK

**Comment by sree526** [comment]
Even with beta.11 version I'm getting the same error

**Comment by cerebroo** [comment]
Downgrading to beta.11 worked for me.

**Comment by nicktobolski** [comment]
@sree526 Did you try `npm install` after changing your package.json to the lesser version?

**Comment by LeandritGo** [comment]
Downgrading to beta.11 did the job for me. Thanks

**Comment by sree526** [comment]
Yup. My bad it worked. But the thing is after downgrading I didn't have to
use this tool. It was accepting md again.

**Comment by ambujsharma23** [comment]
Deprecation of Md have been done in beta.12, therefore beta.11 is working fine without running the tool. 
Can we know when r we getting the next update for the tool so that we can use beta.12 up-gradation.

**Comment by nicktobolski** [comment]
@sree526 these steps worked for me: 
1. make sure you have 2.0.11 in your node_modules dir
2. run migration tool
3. update to 2.0.12

**Comment by TimonRiemslagh** [comment]
I downgraded to "@angular/material": "^2.0.0-beta.10" and it's not working. I'm still having the error "has no exported member MdCheckboxModule". I tried deleting node_modules and installing npm again. I feel like the mat is already in the beta.10 version? How can I make my project build?

**Comment by ambujsharma23** [comment]
@TimonRiemslagh 
1.) I first updated all my packages to get angular ^4.4.4 with _npm update_ as these new changes work with this version,
2.)  Then downgraded to @angular/cdk and @angular/material to ^2.0.0-beta.11 , 
3.) Ran the prefix updater tool which perfectly replaced all Md with mat.
4.) Then finally updated @angular/cdk and @angular/material to ^2.0.0-beta.12, 
Build was working fine in all scenarios.

**Comment by Taisho** [comment]
@TimonRiemslagh followed you steps, still no luck for me

**Comment by DevVersion** [comment]
There are now better instructions if the tool fails. 

As the README explains, any version higher than `beta.11` is not working with the tool. Be sure to **turn-off** auto bumping of the dependencies by a caret (e.g. `^2.0.0-beta.11`)

Closing this issue in meanwhile. Please let me know if you still run into the issue.
