### ISSUE TITLE
The tool doesn't update Stepper imports

### ISSUE THREAD

**Issue by dushkostanoeski** [angular/material-prefix-updater#14]
I ran the tool before upgrading to `beta11` and the tool didn't update the Stepper imports like 
```
import { MdStepperModule } from'@angular/material';
import { MdVerticalStepper } from'@angular/material';
```
It updated 
```
import { MdSidenav } from '@angular/material'; 
```
to 
```
import { MatSidenav } from '@angular/material'; 
```
an everything else.

EDIT:  same goes for `html` tags, the Stepper tags weren't updated.

**Comment by DevVersion** [comment]
Fixed with v0.0.6
