### ISSUE TITLE
README.md code example uses incorrect import statement?

### ISSUE THREAD

**Issue by alexjlockwood** [angular/material-prefix-updater#5]
The `README.md` file suggests to use the following code:

```
import {MATERIAL_COMPATIBILITY_MODE} from '@angular/material';
```

However, this only works when you use `@angular/material/core`.

**Comment by jelbourn** [comment]
@alexjlockwood are you use beta.11? I was able to import that symbol in the material.angular.io app.

**Comment by Splaktar** [comment]
Just `@angular/material` works for me. Angular 4.4.3, AM beta.11, and TypeScript 2.3.4.

**Comment by DevVersion** [comment]
I was not able to reproduce this issue either. I'll be closing this issue for now, but please drop another message if you still run into the same issue.
