### ISSUE TITLE
Feature Request:  Add MATERIAL_COMPATIBILITIY_MODE provider to spec files

### ISSUE THREAD

**Issue by cport1** [angular/material-prefix-updater#9]
Tests broken after migration so you have to manually add this to your spec files. It would be nice if it fixed your spec files too.

**Comment by german-e-mas** [comment]
I had the same issue.

**Comment by technoSpino** [comment]
In my test.ts set up I was able to add it to the init. all tests are now set to mat-
```
getTestBed().initTestEnvironment(
  [BrowserDynamicTestingModule, NoConflictStyleCompatibilityMode],
  platformBrowserDynamicTesting()
);
```

**Comment by Splaktar** [comment]
This doesn't seem to be needed now with beta.12.
